version: "3"

services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - db/database.env
    expose:
      - "5432"

  backend:
    container_name: django
    build: ./django_app/
    command: >
      gunicorn django_app.wsgi:application --bind 0.0.0.0:8899 --workers=4
    env_file:
      - db/database.env
    volumes:
      - ./django_app/:/code/
      - staticfiles:/code/staticfiles/
    expose:
      - "8899"
    depends_on:
      - db

  frontend:
    container_name: react
    build: ./rushr-reactjs/
    command: >
      npm start
    volumes:
      - staticfiles:/app/staticfiles/
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:1.19
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - staticfiles:/code/staticfiles/
    depends_on:
      - frontend

volumes:
  staticfiles:
