# Generated by Django 3.1.6 on 2021-02-06 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='ti_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
