# Generated by Django 3.1.6 on 2021-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b64_encoded', models.TextField()),
                ('chart_type', models.CharField(choices=[('PIE', 'Pie')], max_length=3)),
            ],
        ),
    ]
