# Generated by Django 3.1.6 on 2021-02-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_desc',
            field=models.CharField(default='base', max_length=50),
            preserve_default=False,
        ),
    ]
